export const clamp = (value: number, min: number, max: number) =>
  Math.min(Math.max(value, min), max);

export const AUTH_COLORS = {
  background: '#1C4D8D',
  backgroundDeep: '#1C4D8D',
  backgroundElevated: '#FFFFFF',
  cardDark: '#FFFFFF',
  cardDarkAlt: '#F8FAFC',
  cardBorder: '#E5E7EB',
  cardBorderActive: '#1C4D8D',
  cardLight: '#FFFFFF',
  cardLightBorder: '#E5E7EB',
  tile: '#F8FAFC',
  tileSoft: 'rgba(255,255,255,0.08)',
  primary: '#1C4D8D',
  primaryText: '#ffffff',
  textPrimary: '#111827',
  textSecondary: '#6B7280',
  textMuted: '#6B7280',
  textTertiary: '#9CA3AF',
  inputDark: '#F9FAFB',
  inputDarkBorder: '#E5E7EB',
  inputLight: '#F9FAFB',
  inputLightBorder: '#E5E7EB',
  inputTextDark: '#111827',
  inputTextLight: '#111827',
  placeholderDark: '#94A3B8',
  placeholderLight: '#94A3B8',
  linkLight: '#1C4D8D',
  linkAccent: '#1C4D8D',
  success: '#22C55E',
  warning: '#ff9f1c',
  danger: '#f15c5c',
} as const;
