export const tokens = {
  colors: {
    canvasBlue: '#1C4D8D',
    signedInCanvas: '#FFFFFF',
    launchCanvas: '#F7F8FA',
    launchSurface: '#FFFDFC',
    cardSoft: '#EAF1FB',
    cardStrong: '#1C4D8D',
    onCardStrong: '#FFFFFF',
    sectionText: '#0F2954',
    contentSurface: '#FFFFFF',
    contentMuted: '#F1F5F9',
    onCanvas: '#0F2954',
    onCanvasMuted: '#475569',
    background: '#FFFFFF',
    surface: '#FFFFFF',
    surfaceMuted: '#F1F5F9',
    border: '#E5E7EB',
    text: '#111827',
    textMuted: '#6B7280',
    textSubtle: '#9CA3AF',
    brandDark: '#0F2954',
    brand: '#1C4D8D',
    brandLight: '#4988C4',
    brandAccent: '#1C4D8D',
    brandSoft: '#EAF1FB',
    brandMuted: '#DCE6F7',
    focusRing: '#5F83B3',
    onBrand: '#FFFFFF',
    onBrandMuted: '#CBD5F0',
    success: '#10B981',
    danger: '#EF4444',
    warning: '#F59E0B',
    info: '#0369A1',
    successSoft: '#ECFDF5',
    dangerSoft: '#FEF2F2',
    warningSoft: '#FEF3C7',
    infoSoft: '#E0F2FE',
    white: '#FFFFFF',
  },
  radius: {
    sm: 10,
    md: 14,
    lg: 18,
    pill: 999,
  },
  spacing: {
    xxs: 4,
    xs: 6,
    sm: 10,
    md: 14,
    lg: 18,
    xl: 24,
    xxl: 32,
  },
  typography: {
    h1: 26,
    h2: 22,
    h3: 18,
    body: 14,
    caption: 12,
    label: 14,
    control: 15,
  },
  layout: {
    gutter: 16,
    gutterWide: 20,
    sectionGap: 16,
    tabBarClearance: 24,
    contentMaxWidth: 720,
  },
  controls: {
    minimumTouch: 44,
    fieldHeight: 52,
    buttonHeight: 52,
    compactHeight: 44,
  },
  opacity: {
    disabled: 0.5,
  },
  navigation: {
    iconSize: 22,
    labelSize: 9,
    itemMinHeight: 44,
    barContentHeight: 64,
    barMinHeight: 64,
  },
  shadow: {
    card: {
      shadowColor: '#0f172a',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.08,
      shadowRadius: 18,
      elevation: 4,
    },
  },
} as const;
